#!/usr/bin/env bash
set -euo pipefail

# TODO: maybe
# - install kickstart.nvim
# - install plugins for micro

# Give yadm it's own easily accessible config and ignore
yadm gitconfig include.path ~/.config/yadm/gitconfig

# Install homebrew if its missing
if ! command -v brew &> /dev/null; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Have homebrew add itself to path if it installed
if command -v brew &>/dev/null; then
    eval "$(brew shellenv)"
fi


if [[ -f ~/.config/yadm/essentials.rb ]]; then
    echo "Updating homebrew bundle"
    brew bundle --file="$HOME/.config/yadm/essentials.rb"
fi

# If yazi was installed by brew then add the plugins too
if command -v yazi &> /dev/null; then
    echo "Adding plugins to yazi"
    ya pack -a yazi-rs/plugins:max-preview
    ya pack -a yazi-rs/plugins:full-border
    ya pack -a yazi-rs/plugins:git
    ya pack -a KKV9/command
    ya pack -a imsi32/yatline
    ya pack -a imsi32/yatline-githead
    ya pack -a ndtoan96/ouch
fi

# If eget was installed we can add custom binaries too
# if command -v eget &> /dev/null; then
#     eget grafviktor/goto --to=~/.local/bin
# fi

# if locale-gen exists ensure our locale is okay
if command -v locale-gen &>/dev/null; then
    if ! locale -a | grep -q "en_US.utf8"; then
        sudo locale-gen en_US.UTF-8
    fi
fi


# Do operating system specific actions
# if [ "$system_type" = "Darwin" ]; then
#   echo "Running Darwin specific steps:"

# fi
# else sudo locale-gen en_US.UTF-8

# Set terminal prefs
# if [ -d "$HOME/.config/iterm2" ]; then
#     echo "Setting iTerm preference folder"
#     defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
# fi

echo "Bootstrap complete!"
