
# TODO: prune through this list
# vscode "arthurlobo.easy-codesnap"
vscode "bierner.markdown-preview-github-styles"
# vscode "bierner.markdown-checkbox"
# vscode "bierner.markdown-emoji"
# vscode "bierner.markdown-footnotes"
# vscode "bierner.markdown-mermaid"
# vscode "bierner.markdown-yaml-preamble"
# vscode "bradlc.vscode-tailwindcss"
# vscode "christian-kohler.path-intellisense"
# vscode "continue.continue"
# vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
# vscode "dchanco.vsc-invoke"
# vscode "dotenv.dotenv-vscode"
vscode "eamodio.gitlens"
# vscode "edwinhuish.better-comments-next"
# vscode "github.copilot-chat"
# vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "gruntfuggly.activitusbar"
vscode "gruntfuggly.todo-tree"
vscode "hookyqr.beautify"
vscode "kevinkyang.auto-comment-blocks"
# vscode "llvm-vs-code-extensions.vscode-clangd"
# vscode "matepek.vscode-catch2-test-adapter"
# vscode "meganrogge.template-string-converter"
# vscode "mhutchie.git-graph"
# vscode "ms-azuretools.vscode-containers"
# vscode "ms-vscode.cpptools"
# vscode "ms-vscode.cpptools-extension-pack"
# vscode "ms-vscode.cpptools-themes"
# vscode "ms-vscode.hexeditor"
# vscode "ms-vscode.live-server"
# vscode "mxsdev.typescript-explorer"
vscode "mylesmurphy.prettify-ts"
# vscode "oouo-diogo-perdigao.docthis"
vscode "oven.bun-vscode"
# vscode "pmneo.tsimporter"
vscode "quicktype.quicktype"
# vscode "redhat.vscode-yaml"
# vscode "rhalaly.scope-to-this"
vscode "seunlanlege.action-buttons"
# vscode "shd101wyy.markdown-preview-enhanced"
vscode "spencerwmiles.vscode-task-buttons"
# vscode "spmeesseman.vscode-taskexplorer"
# vscode "stylelint.vscode-stylelint"
vscode "svelte.svelte-vscode"
vscode "sysoev.language-stylus"
# vscode "tamasfe.even-better-toml"
vscode "tht13.rst-vscode"
vscode "tomoki1207.pdf"
vscode "uctakeoff.vscode-counter"
# vscode "vlanguage.vscode-vlang"
# vscode "ycodetech.automatic-comment-blocks"
# vscode "yoavbls.pretty-ts-errors"
# vscode "yzhang.markdown-all-in-one"
# vscode "ziglang.vscode-zig"