[manager]
show_hidden = true
ratio = [0, 4, 4]
linemode = "size_and_mtime"
title_format = "yazi@{cwd}"


[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
